version: '3'
services:
    django
        restart: always
        build: ./django
        expose:
            - "8000"
        networks:
            - nginx_network
        volumes:
            - ./django:/code
        links:
            - redis
        hostname: django-server
    nginx:
        restart: always
        image: nginx
        ports:
            - "80:80"
        networks:
            - nginx_network
        depends_on:
            - django
        volumes:
            - ./nginx/project.conf:/etc/nginx/conf.d/default.conf
    # redis:
    #     restart: always
    #     image: redis:2.8
networks:
    nginx_network:
        driver: bridge
            